# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SurfApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTWebSocket', # Needed for debugging
    'RCTAnimation', # Needed for FlatList and animations running on native UI thread
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  # Third party deps podspec link
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Pods for SurfApp
  pod 'GoogleSignIn', '~> 4.4.0'
  pod 'Firebase/Core'

  # pod 'react-native-icons', :path => '../node_modules/react-native-icons'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-maps', :path => '../node_modules/react-native-maps'

  pod 'react-native-webview', :path => '../node_modules/react-native-webview'


  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  pod 'react-native-geolocation', path: '../node_modules/@react-native-community/geolocation'
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'react-native-video/VideoCaching', :path => '../node_modules/react-native-video/react-native-video.podspec'

  pod 'BugsnagReactNative', :path => '../node_modules/bugsnag-react-native'

  target 'SurfAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SurfApp-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SurfApp-tvOS

  target 'SurfApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

install! 'cocoapods', :deterministic_uuids => false

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
  end
end
